### PR TITLE
Add reduce and actions

### PR DESCRIPTION
**Pull request by silviatofana**
Description
In this step, you will configure your Redux Store and write actions and reducer for adding and removing books. NOTE: editing an existing book and updating the progress is not part of this step. Neither is the styling of the application's components but adding and removing actions need to be implemented.

IMPORTANT NOTE: Read all requirements before you start building your project.

General requirements
Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
Make sure that you used correct flow [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
HTML/CSS requirements
Follow our list of the [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
JavaScript requirements
Follow our list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).
Project requirements
Add Redux Toolkit(npm install react-redux @reduxjs/toolkit).

Structure your application files using a "feature folder" approach and use the [ducks pattern](https://github.com/erikras/ducks-modular-redux) for your Redux files. Your files/folder structure could look like this:

...
/src
    |---/components
    |---/redux
        |--- /books
                | books.js
        |--- /categories
                | categories.js
        | configureStore.js
    | index.js
Write your book's actions and reducer (in /src/redux/books/books.js) using the [ducks pattern](https://github.com/erikras/ducks-modular-redux).

Define action types for adding and removing a book.
Set the initial state to be an empty array of books.
Export Action Creators for your actions.
Write your reducer and export it as default.
Define state changes for the actions that you created.
In case of unknown action - return to the current state.
Write your categories actions and reducer (in /src/redux/categories/categories.js) using the [ducks pattern](https://github.com/erikras/ducks-modular-redux).

Define an action type for checking the status.
Set the initial state to be an empty array of categories.
Export Action Creators for your actions.
Write your reducer and export it as default.
For the check status action return a string "Under construction".
In case of unknown action - return to the current state.
Configure the Redux Store (/src/redux/configureStore.js):

Importing the necessary methods from Redux Toolkit.
Combine both reducers into a root reducer by using the configureStore function.

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @silviatofana, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ All linters are passing
✔️ Professional Readme
✔️ Correct gitflow

## Required 
- [ ] Kindly fix the error which appears when I try to run your app.

Screenshot 2022-07-12 at 12 09 23 AM

- [ ] As your app did not run successfully, I was not able to check the adding and removing of books and also the check status button which displays under construction.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by silviatofana** [comment]
@sja-thedude sorry I just haven't push to add-reduce-and-actions after I solve that error

**Comment by silviatofana** [comment]
@sja-thedude http://localhost:3001/

**Comment by silviatofana** [comment]
@sja-thedude 
image

**Comment by silviatofana** [comment]
@sja-thedude 
image

**Comment by silviatofana** [comment]
@sja-thedude I should submit it again for another review?

**Comment by sja-thedude** [comment]
> @sja-thedude I should submit it again for another review?
> 
> 

@silviatofana Yes you should ask for another review

**Review by BenMukebo — APPROVED** [review]
### Hi @silviatofana, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 




## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] I would also recommend adding the issue link in the contributing sections: 

```
## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).
```

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by silviatofana** [comment]
Thanks

lun., 11 iul. 2022, 22:26 Kasongo Mukebo Ben ***@***.***> a
scris:

**Pull request merged**
